//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class 地址值对象
	{
		public virtual object 城市
		{
			get;
			set;
		}

		public virtual object 邮编
		{
			get;
			set;
		}

		public virtual object 地址一
		{
			get;
			set;
		}

		public virtual object 地址二
		{
			get;
			set;
		}

	}
}

