//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class 日程基类
	{
		public virtual string 主题
		{
			get;
			set;
		}

		public virtual string 内容
		{
			get;
			set;
		}

		public virtual string 重要性
		{
			get;
			set;
		}

		public virtual string 进度
		{
			get;
			set;
		}

		public virtual DateTime 开始时间
		{
			get;
			set;
		}

		public virtual DateTime 结束时间
		{
			get;
			set;
		}

		public virtual bool 是否全天事件
		{
			get;
			set;
		}

		public virtual void 设置任务()
		{
			throw new System.NotImplementedException();
		}

	}
}

