//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Part
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 构型改装通知单
	/// </summary>
	public class Scn
	{
		public virtual IEnumerable<ScnLine> ScnLines
		{
			get;
			set;
		}

	}
}

