//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Project
{
	using Common;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class 任务基类 : 日程基类
	{
		public virtual DateTime 期限
		{
			get;
			set;
		}

		public virtual TimeSpan 工期
		{
			get;
			set;
		}

		public virtual bool 是否里程碑
		{
			get;
			set;
		}

		public virtual string 任务执行者
		{
			get;
			set;
		}

		public virtual string 时区ID
		{
			get;
			set;
		}

		public virtual int 父项ID
		{
			get;
			set;
		}

		public virtual object 可分派资源集合
		{
			get;
			set;
		}

		public virtual 任务基类 父项
		{
			get;
			set;
		}

		public virtual IEnumerable<任务基类> 子项集合
		{
			get;
			set;
		}

		public virtual void 设置任务执行者()
		{
			throw new System.NotImplementedException();
		}

	}
}

